# frozen_string_literal: true

source "https://rubygems.org"

gem "debug", ">= 1.0.0"
gem "sinatra", "~> 3.0", "< 4"
gem "puma", "~> 6.0"
gem "omniauth", "~> 2.0", "< 3"
gem "omniauth-tailscale", path: "../.."
