name: "omniauth-tailscale CI"

on:
  push:
    branches:
      - "main"

  pull_request:

jobs:
  lint:
    runs-on: "ubuntu-latest"
    name: "Lint"
    steps:
      - uses: "actions/checkout@v3"
      - name: "Set up Ruby"
        uses: "ruby/setup-ruby@v1"
        with:
          ruby-version: "2.7.0"
          bundler-cache: true
      - name: "Lint"
        run: "bundle exec standardrb"
